from pyrogram.raw.functions.account import AcceptAuthorization
from pyrogram.raw.functions.account import CancelPasswordEmail
from pyrogram.raw.functions.account import ChangePhone
from pyrogram.raw.functions.account import CheckUsername
from pyrogram.raw.functions.account import ConfirmPasswordEmail
from pyrogram.raw.functions.account import ConfirmPhone
from pyrogram.raw.functions.account import CreateTheme
from pyrogram.raw.functions.account import DeleteAccount
from pyrogram.raw.functions.account import DeleteSecureValue
from pyrogram.raw.functions.account import FinishTakeoutSession
from pyrogram.raw.functions.account import GetAccountTTL
from pyrogram.raw.functions.account import GetAllSecureValues
from pyrogram.raw.functions.account import GetAuthorizationForm
from pyrogram.raw.functions.account import GetAuthorizations
from pyrogram.raw.functions.account import GetAutoDownloadSettings
from pyrogram.raw.functions.account import GetContactSignUpNotification
from pyrogram.raw.functions.account import GetContentSettings
from pyrogram.raw.functions.account import GetGlobalPrivacySettings
from pyrogram.raw.functions.account import GetMultiWallPapers
from pyrogram.raw.functions.account import GetNotifyExceptions
from pyrogram.raw.functions.account import GetNotifySettings
from pyrogram.raw.functions.account import GetPassword
from pyrogram.raw.functions.account import GetPasswordSettings
from pyrogram.raw.functions.account import GetPrivacy
from pyrogram.raw.functions.account import GetSecureValue
from pyrogram.raw.functions.account import GetTheme
from pyrogram.raw.functions.account import GetThemes
from pyrogram.raw.functions.account import GetTmpPassword
from pyrogram.raw.functions.account import GetWallPaper
from pyrogram.raw.functions.account import GetWallPapers
from pyrogram.raw.functions.account import GetWebAuthorizations
from pyrogram.raw.functions.account import InitTakeoutSession
from pyrogram.raw.functions.account import InstallTheme
from pyrogram.raw.functions.account import InstallWallPaper
from pyrogram.raw.functions.account import RegisterDevice
from pyrogram.raw.functions.account import ReportPeer
from pyrogram.raw.functions.account import ResendPasswordEmail
from pyrogram.raw.functions.account import ResetAuthorization
from pyrogram.raw.functions.account import ResetNotifySettings
from pyrogram.raw.functions.account import ResetWallPapers
from pyrogram.raw.functions.account import ResetWebAuthorization
from pyrogram.raw.functions.account import ResetWebAuthorizations
from pyrogram.raw.functions.account import SaveAutoDownloadSettings
from pyrogram.raw.functions.account import SaveSecureValue
from pyrogram.raw.functions.account import SaveTheme
from pyrogram.raw.functions.account import SaveWallPaper
from pyrogram.raw.functions.account import SendChangePhoneCode
from pyrogram.raw.functions.account import SendConfirmPhoneCode
from pyrogram.raw.functions.account import SendVerifyEmailCode
from pyrogram.raw.functions.account import SendVerifyPhoneCode
from pyrogram.raw.functions.account import SetAccountTTL
from pyrogram.raw.functions.account import SetContactSignUpNotification
from pyrogram.raw.functions.account import SetContentSettings
from pyrogram.raw.functions.account import SetGlobalPrivacySettings
from pyrogram.raw.functions.account import SetPrivacy
from pyrogram.raw.functions.account import UnregisterDevice
from pyrogram.raw.functions.account import UpdateDeviceLocked
from pyrogram.raw.functions.account import UpdateNotifySettings
from pyrogram.raw.functions.account import UpdatePasswordSettings
from pyrogram.raw.functions.account import UpdateProfile
from pyrogram.raw.functions.account import UpdateStatus
from pyrogram.raw.functions.account import UpdateTheme
from pyrogram.raw.functions.account import UpdateUsername
from pyrogram.raw.functions.account import UploadTheme
from pyrogram.raw.functions.account import UploadWallPaper
from pyrogram.raw.functions.account import VerifyEmail
from pyrogram.raw.functions.account import VerifyPhone
