from pyrogram.raw.functions.channels import CheckUsername
from pyrogram.raw.functions.channels import CreateChannel
from pyrogram.raw.functions.channels import DeleteChannel
from pyrogram.raw.functions.channels import DeleteHistory
from pyrogram.raw.functions.channels import DeleteMessages
from pyrogram.raw.functions.channels import DeleteUserHistory
from pyrogram.raw.functions.channels import EditAdmin
from pyrogram.raw.functions.channels import EditBanned
from pyrogram.raw.functions.channels import EditCreator
from pyrogram.raw.functions.channels import EditLocation
from pyrogram.raw.functions.channels import EditPhoto
from pyrogram.raw.functions.channels import EditTitle
from pyrogram.raw.functions.channels import ExportMessageLink
from pyrogram.raw.functions.channels import GetAdminLog
from pyrogram.raw.functions.channels import GetAdminedPublicChannels
from pyrogram.raw.functions.channels import GetChannels
from pyrogram.raw.functions.channels import GetFullChannel
from pyrogram.raw.functions.channels import GetGroupsForDiscussion
from pyrogram.raw.functions.channels import GetInactiveChannels
from pyrogram.raw.functions.channels import GetLeftChannels
from pyrogram.raw.functions.channels import GetMessages
from pyrogram.raw.functions.channels import GetParticipant
from pyrogram.raw.functions.channels import GetParticipants
from pyrogram.raw.functions.channels import InviteToChannel
from pyrogram.raw.functions.channels import JoinChannel
from pyrogram.raw.functions.channels import LeaveChannel
from pyrogram.raw.functions.channels import ReadHistory
from pyrogram.raw.functions.channels import ReadMessageContents
from pyrogram.raw.functions.channels import ReportSpam
from pyrogram.raw.functions.channels import SetDiscussionGroup
from pyrogram.raw.functions.channels import SetStickers
from pyrogram.raw.functions.channels import TogglePreHistoryHidden
from pyrogram.raw.functions.channels import ToggleSignatures
from pyrogram.raw.functions.channels import ToggleSlowMode
from pyrogram.raw.functions.channels import UpdateUsername
